---
title: "Sokhan-Fulfillment-Project"
author: "Serhiy Sokhan"
date: "10/19/2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

#Loading in my libraries.
```


```{r, echo = FALSE, message = FALSE}

#I was very fortunate in my search for a dataset.  From the beginning of this course, I knew that I wanted to analyze the 10,000+ orders from my time as the Web Fulfillment Manager of The Harvard Shop.  However, I was not sure of the variables that I wanted to work with.  I decided to make each entry an individual month for a certain country.  I then decided to examine the countries that the orders were sent to each month, the total amount of sales for each country and month, and the average order value.  Before deciding on making each entry an individual month for a certain country, I also considered making each observation a day and each observation a month.  However, these two alternative options each had their own issues.  I concluded that analyzing daily sales data will not be as useful for identifying trends for my successor.  I also concluded that analyzing monthly sales data would not be as useful because it would only have 12 observations. Consequently, I decided to make each observation a month and country.  Getting this data was fortunately relatively simple and straightforward.  The Harvard Shop uses the e-commerce platform Shopify.  Shopify is an avid supporter of using data in business frequently to allow retailers to identify trends and make data-driven decisions. As such, the platform does a fantastic job of providing clean data that can be exported easily. I was able to export the data with the exact variables that I needed for my analysis.  Of course, I purposely exported and used data that does not reveal any information about unique orders or customers. 


monthandcountry <- read_csv("Sales-11-01-17-to-10-18-18-country-month.csv")

fulfillment_data <- monthandcountry

write_rds(fulfillment_data, "Sokhan-Fulfillment-Project/fulfillment_data.rds")


#Above, I read in the .csv file from the Shopify export.  Then, I named that fulfillment_data, and used write_rds for use in my Shiny App.

```
